name: Caching Dependencies

on:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js Version
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies if Cache not saved
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install
      
      
      - name: Check Cache Hit
        if: steps.cache-node.outputs.cache-hit == 'true'
        run: echo 'Cache Hit!!'
      
      - name: Build
        run: npm build
        

